dailyexpense/account/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v
urlpatterns = [
    path('register',v.add_user,name="adduser"), 
    path('-login',v.login_view,name="login"), 
    path('-logout',v.logout_view,name="logout"), 
    path('-update-profile',v.edit_profile,name="editprofile"), 
]

# appname mappingName
# url

dailyexpense/dailyexpense/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home), 
    path('acc',include(('account.urls',"account"),namespace="account")),
    path('inc',include(('income.urls',"income"),namespace="income")),
    path('exp',include(('expense.urls',"expense"),namespace="expense")),

] 

dailyexpense/expense/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v
urlpatterns = [
    path('expense',v.add_expense,name='addexpense'),
    path('-expenselist',v.expense_list,name='expl'),
]

dailyexpense/income/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v
urlpatterns = [
    path('income', v.add_income,name="addincome"),
    path('-incomelist', v.income_list,name="incl"),
    path('delete_income/<int:id>',v.income_delete,name="income_delete"),
]

dailyexpense/account/models.py
from django.db import models

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

from django import forms

class UserInfo(User):
    age=models.IntegerField()
    gender=models.CharField(max_length=30)
    contact=models.CharField(max_length=15)
    class Meta:
        db_table="userinfo"

class UserForm(UserCreationForm):
    class Meta:
        model=UserInfo
        fields=['username','first_name','last_name',"age","contact","gender",'email','password1','password2']

dailyexpense/expense/models.py
from django.db import models
from django.contrib.auth.models import User

class Expense(models.Model):
    expense=models.IntegerField()
    expenseType=models.CharField(max_length=30)
    expenseDate=models.DateField() #auto_now=True
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

from django import forms
class ExpenseForm(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'

dailyexpense/income/models.py
from django.db import models
from django.contrib.auth.models import User

class Income(models.Model):
    income=models.IntegerField()
    incomeType=models.CharField(max_length=30)
    incomeDate=models.DateField() #auto_now=True
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

from django import forms

class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields=['income','incomeType','incomeDate','description']

dailyexpense/account/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import User,UserInfo,UserForm
from expense.models import Expense
from income.models import Income

def getbalance(request):
    uid=request.session.get("userid")
    incl=Income.objects.filter(user=uid)
    expl=Expense.objects.filter(user=uid)
    totalIncome=0
    totalExpense=0

    for i in incl:
        totalIncome=totalIncome+i.income
    
    for i in expl:
        totalExpense=totalExpense+i.expense
    return totalIncome-totalExpense


def home(request):
    for i in request.session.items():
        print(" ---------- ",i)
    return render(request,'home.html',{'bal':getbalance(request)})

def add_user(request):

    if request.method=='POST': 
        f=UserForm(request.POST)
        f.save()
        return redirect('/')
    else:
        f=UserForm
        d={'form':f}
        return render(request,'form.html',d) 

from django.contrib.auth import authenticate,login,logout
def login_view(request):

    if request.method=='POST': 
        uname=request.POST.get('uname')
        passw=request.POST.get('passw')
        user=authenticate(request,username=uname,password=passw)
        if user is not None:
            request.session['userid']=user.id
            login(request,user)
            return redirect('/')
        else:
            return HttpResponse("InValid UserName ANd Password")
    else:
        return render(request,'login.html') 


def logout_view(request):
    logout(request)
    return redirect('/')

def edit_profile(request):
    uid=request.session.get("userid")
    us=UserInfo.objects.get(id=uid)
    if request.method=='POST':
        f=UserForm(request.POST,instance=us)
        f.save()
        return redirect('/')
    else:    
        f=UserForm(instance=us)
        return render(request,'form.html',{'form':f})

dailyexpense/expense/views.py
from django.shortcuts import render,redirect
from account.views import getbalance
from .models import Expense,ExpenseForm


def add_expense(request):

    if request.method=='POST':
        f=ExpenseForm(request.POST)
        #if getbalance(request)>
        f.save()
        return redirect('/')
    else:
        f=ExpenseForm
        d={'form':f}
        return render(request,'form.html',d)

def expense_list(request):
    userid=request.session.get("userid")
    expl=Expense.objects.filter(user=userid)
    return render(request,'expenselist.html',{'exp':expl})

dailyexpense/income/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import Income,IncomeForm

def add_income(request):

    if request.method=='POST':
        f=IncomeForm(request.POST)
        #userid=request.session.get("userid")
        #us=User.objects.get(id=userid)
        #f.user=us
        f.save()
        return redirect('/')
    else:
        f=IncomeForm
        d={'form':f}
        return render(request,'form.html',d)

def income_list(request):
    userid=request.session.get("userid")
    incl=Income.objects.filter(user=userid)
    inc=set()
    dl=set()
    inct=set()
    for i in incl:
        inc.add(i.income)
    
    for i in incl:
        dl.add(i.incomeType)
    
    for i in incl:
        inct.add(i.incomeDate)
        

    d={'inc':incl,"income":inc,"inct":inct,"dl":dl}
    return render(request,'incomelist.html',d)

def income_delete(request,id):
    income=Income.objects.get(id=id)
    income.delete()
    return redirect('/')

dailyexpense/account/templates/base.html
<style>
    .sidebar {
        width: 200px;
        height: 100%;
        position: fixed;
        left: 0;
        top: 0;
        background-color: darkblue;
    }
    
    .sidebar a {
        padding: 30px;
        text-decoration: none;
        color: darkgray;
    }
    
    .sidebar a:hover {
        color: lime;
    }
    
    .main {
        padding-left: 200px;
    }
</style>

<div class="sidebar">
    {%if user.is_authenticated%}
    <h1 style="color: red;"> {{user}}</h1>
    {%endif%}
    <h2><a href="/">Home</a></h2>

    {%if user.is_authenticated%}

    <h2><a href="{%url 'account:editprofile'%}">EditProfile</a></h2>
    <h2><a href="{%url 'income:addincome'%}">AddIncome</a></h2>
    <h2><a href="{%url 'expense:addexpense'%}">AddExpense</a></h2>
    <h2><a href="{%url 'income:incl'%}">IncomeList</a></h2>
    <h2><a href="{%url 'expense:expl'%}">ExpenseList</a></h2>
    <h2><a href="{%url 'account:logout'%}">Logout</a></h2>

    {%else%}

    <h2><a href="{%url 'account:adduser'%}">Registre</a></h2>
    <h2><a href="{%url 'account:login'%}">Login</a></h2>


    {%endif%}

    <h2><a href="">Contact-Us</a></h2>

</div>

<div class="main">
    {%block data%} {%endblock%}
</div>

dailyexpense/account/templates/form.html
{%extends 'base.html'%} {%block data%}
<form method="POST">
    {%csrf_token%}
    <table>
        {{form.as_table}}
        <tr>
            <td><input type="submit"></td>
            <td><input type="reset"></td>
        </tr>
    </table>


</form>

{%endblock%}

dailyexpense/account/templates/home.html
{%extends 'base.html'%} {%block data%}
<h1>Daily Income Expense Management Application</h1>

{%if user.is_authenticated%}
<h2> Welcome :<span style="color: green;"> {{user.first_name}} &nbsp;&nbsp;&nbsp; {{user.last_name}}</h2>
<h2>Your Total Balance is  : <span style="color: red;">{{bal}}</span></h2>
{%endif%} {%endblock%}

dailyexpense/account/templates/login.html
{%extends 'base.html'%} {%block data%}
<form method="POST">
    {%csrf_token%}
    <table cellspacing="10" border="1">
        <tr>
            <td>UserName</td>
            <td><input type="text" name="uname"></td>
        </tr>

        <tr>
            <td>Password</td>
            <td><input type="password" name="passw"></td>
        </tr>

        <tr>
            <td><input type="submit" value="LOGIN"></td>
            <td><button><a href="{%url 'account:adduser'%}">Registre</a></button></td>
        </tr>
    </table>
</form>
{%endblock%}

dailyexpense/expense/templates/expenselist.html
{%extends 'base.html'%} {%block data%}
<h1> All Expense Details</h1>

<table cellspacing="10" border="1">
    <tr>
        <th>Id</th>
        <th>Expense</th>
        <th>ExpenseType</th>
        <th>ExpenseDate</th>
        <th>Discription</th>
        <th>User</th>
    </tr>
    {% for i in exp%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.expense}}</td>
        <td>{{i.expenseType}}</td>
        <td>{{i.expenseDate}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
    </tr>
    {%endfor%}
</table>
{%endblock%}

dailyexpense/expense/templates/form.html
<form method="POST">
    {%csrf_token%}
    <table>
        {{form.as_table}}
        <tr>
            <td>UserName</td>
            <td><input type="text" name="user" value="{{user}}"></td>
        </tr>
        <tr>
            <td><input type="submit"></td>
            <td><input type="reset"></td>
        </tr>
    </table>


</form>

dailyexpense/income/templates/form.html
<form method="POST">
    {%csrf_token%}
    <table>
        {{form.as_table}}
        <tr>
            <td>UserName</td>
            <td><input type="text" name="user" value="{{user}}"></td>
        </tr>
        <tr>
            <td><input type="submit"></td>
            <td><input type="reset"></td>
        </tr>
    </table>


</form>

dailyexpense/income/templates/incomelist.html
{%extends 'base.html'%} {%block data%}
<h1> All Income Details</h1>

<table cellspacing="10" border="1">
    <tr>
        <th>Id</th>
        <th>Income</th>
        <th>IncomeType</th>
        <th>IncomeDate</th>
        <th>Discription</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>
    {% for i in inc%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.incomeType}}</td>
        <td>{{i.incomeDate}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href="{%url 'income:income_delete' i.id %}">Delete</a></td>
        <td><a href="">Edit</a></td>
    </tr>
    {%endfor%}
</table>

<style>
    .rside {
        width: 260px;
        height: 100%;
        position: fixed;
        right: 0%;
        top: 0%;
        background-color: hotpink;
    }
</style>
<div class="rside">
    <h1> By Salary</h1>
    {%for i in income%}
    <h2><a href="">{{i}}</a></h2>
    {%endfor%}
    <h1> By Salary-Type</h1>
    {%for i in inct%}
    <h2><a href="">{{i}}</a></h2>
    {%endfor%}
    <h1> By Salary-Date</h1>
    {%for i in dl%}
    <h2><a href="">{{i}}</a></h2>
    {%endfor%}
</div>

{%endblock%}